name: Code Quality with SonarCloud, Detekt and Ktlint

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: Code

      - name: Run Detekt
        run: ./gradlew detekt
        working-directory: Code

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ./Code
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Prepare reports for GitHub Pages
        run: |
          mkdir -p reports
          cp Code/app/build/reports/detekt/detekt.html reports/detekt.html || echo "Detekt report not found"
          cp Code/app/build/reports/ktlint/ktlint.html reports/ktlint.html || echo "Ktlint report not found"

      - name: Publish report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          publish_branch: gh-pages
          force_orphan: true

